language: php

php:
  - 5.4

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source

script: vendor/bin/codecept run --coverage --xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_log/coverage.xml

branches:
  only:
    - master